---
- hosts: servers
  become: yes
  gather_facts: yes

  vars:
    - conteudo_h1: 'Neste servidor tem um {{ ansible_hostname }}!'
  tasks:
    - name: Mudar string do template para nome da distro
      lineinfile:
        path: /var/www/html/index.html
        regexp: <h1>.*</h1>
        line: '<h1>{{ conteudo_h1 }}</h1>'
        state: present
