---
- hosts: servers
  become: yes
  gather_facts: yes

  tasks:
    - name: Mudar string do template para nome da distro
      lineinfile:
        path: /var/www/html/index.html
        regexp: '<h1>Hi, my name is Forty</h1>'
        line: '<h1>Neste servidor tem um {{ ansible_hostname }}!</h1>'
        state: present
