---
- hosts: servers
  become: yes
  gather_facts: yes

  vars:
    - titulo_da_pagina: null

  tasks:
    - name: Mudar título da página
      lineinfile:
        path: /var/www/html/index.html
        regexp: '<title>.*</title>'
        line: '<title>{{ titulo_da_pagina }}</title>'
        state: present
